try polling since kubectl wait hangs

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -175,12 +175,26 @@ jobs:
         run: |
           just deploy bridge-tester $TAG
           kubectl get job bridge-tester-chart -n astria-dev-cluster
-          while ! kubectl wait --for=condition=complete --timeout=300s job/bridge-tester-chart -n astria-dev-cluster; do sleep 1; done
-          JOB_STATUS=$(kubectl get job bridge-tester-chart -o jsonpath='{.status.succeeded}' -n astria-dev-cluster)
-          if [ "$JOB_STATUS" != "1" ]; then
-            echo "Job failed"
-            exit 1
-          fi
+          ATTEMPTS=0
+          MAX_ATTEMPTS=30
+          SLEEP_TIME=5
+          while [ $ATTEMPTS -lt $MAX_ATTEMPTS ]; do
+            JOB_STATUS=$(kubectl get job bridge-tester-chart -n astria-dev-cluster -o jsonpath='{.status.succeeded}')
+            if [ "$JOB_STATUS" == "1" ]; then
+              echo "Job succeeded"
+              exit 0
+            fi
+            JOB_FAILED=$(kubectl get job bridge-tester-chart -n astria-dev-cluster -o jsonpath='{.status.failed}')
+            if [ "$JOB_FAILED" == "1" ]; then
+              echo "Job failed"
+              exit 1
+            fi
+            echo "Waiting for job to complete..."
+            ATTEMPTS=$((ATTEMPTS + 1))
+            sleep $SLEEP_TIME
+          done
+          echo "Job did not complete within the expected time"
+          exit 1
 
   docker:
     if: ${{ always() && !cancelled() }}
